# Generated by Django 5.0.7 on 2025-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Designates a seeded demo account that can be hidden in production views.'),
        ),
    ]
