# Generated by Django 5.0.7 on 2025-10-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Designates a seeded demo account that may be hidden in production views.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.employmentgrade'),
        ),
    ]
