# Generated by Django 5.0.7 on 2025-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employmentgrade_alter_customuser_is_demo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('junior_staff', 'Junior Staff'), ('senior_staff', 'Senior Staff'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin')], default='junior_staff', max_length=20),
        ),
    ]
