# Generated by Django 5.0.7 on 2025-10-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('junior_staff', 'Junior Staff'), ('senior_staff', 'Senior Staff'), ('manager', 'Manager'), ('hr', 'HR'), ('ceo', 'CEO'), ('admin', 'Admin')], default='junior_staff', max_length=20),
        ),
    ]
