# Generated by Django 5.2.6 on 2025-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leaverequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
