# Generated by Django 5.0.7 on 2025-10-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leaverequest_total_days'),
        ('users', '0004_employmentgrade_alter_customuser_is_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGradeEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitled_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='users.employmentgrade')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entitlements', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'Grade Entitlement',
                'verbose_name_plural': 'Grade Entitlements',
                'ordering': ['grade__name', 'leave_type__name'],
                'unique_together': {('grade', 'leave_type')},
            },
        ),
    ]
