# Generated by Django 5.0.7 on 2025-10-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_submitted', 'Leave Request Submitted'), ('leave_manager_approved', 'Leave Request Approved by Manager'), ('leave_hr_approved', 'Leave Request Approved by HR'), ('leave_approved', 'Leave Request Fully Approved'), ('leave_rejected', 'Leave Request Rejected'), ('leave_cancelled', 'Leave Request Cancelled'), ('balance_low', 'Leave Balance Low'), ('system', 'System Notification')], max_length=30),
        ),
    ]
